window.textDatabase = {
    "es": {
        "quotes": {
            "facil": [
                "El Imperio romano fue el periodo de la civilización romana posterior a la República y caracterizado por una forma de gobierno autocrática.",
                "El Antiguo Egipto (en egipcio: Kumat; jeroglíficos: ) fue una civilización de la Antigüedad que se originó a lo largo del cauce medio y bajo del río Nilo y cuya historia abarca más de 3181 años (solamente superada por la maya, con 3697 años).",
                "Renacimiento es el nombre dado en el siglo XIX a un amplio movimiento cultural que se produjo en Europa Occidental durante los siglos XV y XVI. Fue un periodo de transición entre la Edad Media y los inicios de la Edad Moderna.",
                "La Revolución francesa (en francés: Révolution franaise) fue un conflicto social y político, con diversos periodos de violencia, que convulsionó la Francia del Antiguo Régimen, y a otros países por extensión de sus implicaciones.",
                "El término maya (también, Maia) hace referencia a varios artículos:",
                "El Imperio incaico, Imperio inca, Tahuantinsuyo (en quechua: Tawantinsuyu, de tawa 'cuatro', -ntin 'sufijo inclusivo', y suyu 'región', es decir, 'región de las cuatro [partes]'), también llamado Imperio quechua o quichua, fue el imperio más extenso de América precolombina.Surgió en los Andes peruanos entre los siglos XV y XVI, a partir de la expansión del curacazgo del Cuzco y constituyó el período de mayor apogeo de la civilización incaica.",
                "La Revolución Industrial o Primera Revolución Industrial fue el proceso de transformación económica, social y tecnológica que se inició en la segunda mitad del XVIII con la invención y aplicación práctica de la máquina de vapor perfeccionada por James Watt en el Reino de Gran Bretaña y que se extendió décadas después a gran parte de Europa Occidental y la América Anglosajona, concluyendo entre 1820 y 1840.",
                "La Edad Media, el Medievo o el Medioevo es el período histórico de la civilización occidental comprendido entre los siglos v y xv, sucesor de la Edad Antigua y predecesor de la Edad Moderna.",
                "La Guerra Fría fue un enfrentamiento político, económico, social, ideológico, militar y propagandístico que tuvo lugar después de la Segunda Guerra Mundial entre dos bloques principales, occidental (capitalista) y oriental (comunista), liderados respectivamente por los Estados Unidos y la Unión Soviética."
            ],
            "normal": [
                "El Imperio romano fue el periodo de la civilización romana posterior a la República y caracterizado por una forma de gobierno autocrática. En su apogeo controló un territorio que abarcaba desde el océano Atlántico al oeste hasta las orillas del mar Caspio y Rojo al este, y desde el desierto del Sahara al sur hasta las orillas de los ríos Rin y Danubio y la frontera con Caledonia al norte.",
                "El Antiguo Egipto (en egipcio: Kumat; jeroglíficos: ) fue una civilización de la Antigüedad que se originó a lo largo del cauce medio y bajo del río Nilo y cuya historia abarca más de 3181 años (solamente superada por la maya, con 3697 años). El área del antiguo Egipto ha variado a lo largo de los siglos, pero en general se acepta que abarcaba desde el delta del Nilo en el norte, hasta Elefantina, en la primera catarata del Nilo, en el sur.",
                "Renacimiento es el nombre dado en el siglo XIX a un amplio movimiento cultural que se produjo en Europa Occidental durante los siglos XV y XVI. Fue un periodo de transición entre la Edad Media y los inicios de la Edad Moderna. Sus principales exponentes se hallan en el campo de las artes, aunque también se produjo una renovación en las ciencias, tanto naturales como humanas.",
                "La Revolución francesa (en francés: Révolution franaise) fue un conflicto social y político, con diversos periodos de violencia, que convulsionó la Francia del Antiguo Régimen, y a otros países por extensión de sus implicaciones. Se inició con la autoproclamación del Tercer Estado como Asamblea Nacional en 1789 y finalizó con el golpe de Estado de Napoleón Bonaparte en 1799, culminando un proceso de diez años.",
                "El Imperio incaico, Imperio inca, Tahuantinsuyo (en quechua: Tawantinsuyu, de tawa 'cuatro', -ntin 'sufijo inclusivo', y suyu 'región', es decir, 'región de las cuatro [partes]'), también llamado Imperio quechua o quichua, fue el imperio más extenso de América precolombina.Surgió en los Andes peruanos entre los siglos XV y XVI, a partir de la expansión del curacazgo del Cuzco y constituyó el período de mayor apogeo de la civilización incaica. En su máxima extensión abarcó aproximadamente 2 000 000 km, desde el río Ancasmayo, en la actual Colombia, hasta el río Maule, en Chile, limitando al oeste con el océano Pacífico y al este con la selva amazónica y el Gran Chaco.",
                "La Revolución Industrial o Primera Revolución Industrial fue el proceso de transformación económica, social y tecnológica que se inició en la segunda mitad del XVIII con la invención y aplicación práctica de la máquina de vapor perfeccionada por James Watt en el Reino de Gran Bretaña y que se extendió décadas después a gran parte de Europa Occidental y la América Anglosajona, concluyendo entre 1820 y 1840. Durante este periodo se vivió el mayor conjunto de transformaciones económicas y tecnológicas de la historia de la humanidad desde el Neolítico, que vio el paso desde una economía basada fundamentalmente en la agricultura, el comercio a una economía de carácter urbano, industrializada y mecanizada. La Revolución Industrial marca un punto de inflexión en la historia, modificando e influenciando todos los aspectos de la vida cotidiana de una u otra manera.",
                "La Edad Media, el Medievo o el Medioevo es el período histórico de la civilización occidental comprendido entre los siglos v y xv, sucesor de la Edad Antigua y predecesor de la Edad Moderna. Convencionalmente, su inicio se sitúa en el año 476 con la caída del Imperio romano de Occidente y su fin en 1492 con el descubrimiento de América, o en 1453 con la caída de Constantinopla, fecha que tiene la singularidad de coincidir con la invención de la imprenta publicación de la Biblia de Gutenberg y con el fin de la guerra de los Cien Años entre Francia e Inglaterra.",
                "La Guerra Fría fue un enfrentamiento político, económico, social, ideológico, militar y propagandístico que tuvo lugar después de la Segunda Guerra Mundial entre dos bloques principales, occidental (capitalista) y oriental (comunista), liderados respectivamente por los Estados Unidos y la Unión Soviética. El inicio de este periodo se remonta a 1945."
            ],
            "dificil": [
                "El Imperio romano fue el periodo de la civilización romana posterior a la República y caracterizado por una forma de gobierno autocrática. En su apogeo controló un territorio que abarcaba desde el océano Atlántico al oeste hasta las orillas del mar Caspio y Rojo al este, y desde el desierto del Sahara al sur hasta las orillas de los ríos Rin y Danubio y la frontera con Caledonia al norte. Debido a su vasta extensión y duración, las instituciones y la cultura romana tuvieron una influencia profunda y duradera en el desarrollo de la lengua, religión, arquitectura, literatura y leyes en el territorio que gobernaba.",
                "El Antiguo Egipto (en egipcio: Kumat; jeroglíficos: ) fue una civilización de la Antigüedad que se originó a lo largo del cauce medio y bajo del río Nilo y cuya historia abarca más de 3181 años (solamente superada por la maya, con 3697 años). El área del antiguo Egipto ha variado a lo largo de los siglos, pero en general se acepta que abarcaba desde el delta del Nilo en el norte, hasta Elefantina, en la primera catarata del Nilo, en el sur. Además controlaba el desierto oriental, la línea costera del mar Rojo, la península del Sinaí, y un gran territorio occidental dominando los dispersos oasis.",
                "Renacimiento es el nombre dado en el siglo XIX a un amplio movimiento cultural que se produjo en Europa Occidental durante los siglos XV y XVI. Fue un periodo de transición entre la Edad Media y los inicios de la Edad Moderna. Sus principales exponentes se hallan en el campo de las artes, aunque también se produjo una renovación en las ciencias, tanto naturales como humanas. La ciudad de Florencia, en Italia, fue el lugar de nacimiento y desarrollo de este movimiento, que se extendió después por toda Europa.",
                "La Revolución francesa (en francés: Révolution franaise) fue un conflicto social y político, con diversos periodos de violencia, que convulsionó la Francia del Antiguo Régimen, y a otros países por extensión de sus implicaciones. Se inició con la autoproclamación del Tercer Estado como Asamblea Nacional en 1789 y finalizó con el golpe de Estado de Napoleón Bonaparte en 1799, culminando un proceso de diez años. Si bien después de que la Primera República cayó tras el golpe de Estado de Napoleón, la organización política de Francia durante el siglo XIX osciló entre república, imperio y monarquía constitucional, la revolución marcó el final definitivo del feudalismo y del absolutismo en el país, y dio a luz a un nuevo régimen donde la burguesía, que empleaba en ocasiones a las masas populares, se convirtió en la fuerza política dominante.",
                "El Imperio incaico, Imperio inca, Tahuantinsuyo (en quechua: Tawantinsuyu, de tawa 'cuatro', -ntin 'sufijo inclusivo', y suyu 'región', es decir, 'región de las cuatro [partes]'), también llamado Imperio quechua o quichua, fue el imperio más extenso de América precolombina.Surgió en los Andes peruanos entre los siglos XV y XVI, a partir de la expansión del curacazgo del Cuzco y constituyó el período de mayor apogeo de la civilización incaica. En su máxima extensión abarcó aproximadamente 2 000 000 km, desde el río Ancasmayo, en la actual Colombia, hasta el río Maule, en Chile, limitando al oeste con el océano Pacífico y al este con la selva amazónica y el Gran Chaco. El origen del Imperio se remonta a la victoria de Pachacútec sobre la confederación chanca en la batalla de Yahuarpampa, alrededor de 1438.",
                "La Revolución Industrial o Primera Revolución Industrial fue el proceso de transformación económica, social y tecnológica que se inició en la segunda mitad del XVIII con la invención y aplicación práctica de la máquina de vapor perfeccionada por James Watt en el Reino de Gran Bretaña y que se extendió décadas después a gran parte de Europa Occidental y la América Anglosajona, concluyendo entre 1820 y 1840. Durante este periodo se vivió el mayor conjunto de transformaciones económicas y tecnológicas de la historia de la humanidad desde el Neolítico, que vio el paso desde una economía basada fundamentalmente en la agricultura, el comercio a una economía de carácter urbano, industrializada y mecanizada. La Revolución Industrial marca un punto de inflexión en la historia, modificando e influenciando todos los aspectos de la vida cotidiana de una u otra manera. La producción tanto agrícola como de la naciente industria se multiplicó a la vez que disminuía el tiempo de producción.",
                "La Edad Media, el Medievo o el Medioevo es el período histórico de la civilización occidental comprendido entre los siglos v y xv, sucesor de la Edad Antigua y predecesor de la Edad Moderna. Convencionalmente, su inicio se sitúa en el año 476 con la caída del Imperio romano de Occidente y su fin en 1492 con el descubrimiento de América, o en 1453 con la caída de Constantinopla, fecha que tiene la singularidad de coincidir con la invención de la imprenta publicación de la Biblia de Gutenberg y con el fin de la guerra de los Cien Años entre Francia e Inglaterra. Con esto dicho, considerando la caída del Imperio romano de Occidente hasta el descubrimiento de América, la Edad Media abarcó un periodo de 1016 años.",
                "La Guerra Fría fue un enfrentamiento político, económico, social, ideológico, militar y propagandístico que tuvo lugar después de la Segunda Guerra Mundial entre dos bloques principales, occidental (capitalista) y oriental (comunista), liderados respectivamente por los Estados Unidos y la Unión Soviética. El inicio de este periodo se remonta a 1945. Después de la Segunda Guerra Mundial, los Estados Unidos temían la expansión del comunismo y buscaban frenar la influencia soviética en Europa."
            ]
        },
        "jokes": {
            "facil": [],
            "normal": [],
            "dificil": []
        },
        "code": {
            "facil": [],
            "normal": [],
            "dificil": []
        },
        "tongue": {
            "facil": [],
            "normal": [],
            "dificil": []
        }
    }
};
